language: node_js

node_js:
  - 'node'
  - 'lts/*'

services:
  - xvfb

script:
  - node ./internals/scripts/generate-templates-for-linting
  - yarn test -- --maxWorkers=4
  - yarn run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

notifications:
  email:
    on_failure: change

after_success: 'yarn run coveralls'

cache:
  directories:
    - node_modules
